### ISSUE TITLE
Message d'erreur du plugin

### ISSUE THREAD

**Issue by TechGLPI** [departement-maine-et-loire/transferticketentity#10]
Bonjour,

Quand je veux utiliser le plugin dans un ticket j'ai ce message d'erreur : Aucun groupe trouvé avec le droit « Attribué à », transfert impossible.

pouvez me dire pourquoi ? J'ai beau chercher j'ai aucune erreur de droit dans le groupe et en plus je suis positionné sur l'admin.

Merci de votre aide

**Comment by YannickComba** [comment]
Bonjour,

Le plugin actuel requiert qu'une entité autre que celle du ticket actuel ait un groupe avec le droit "Attribué à" (Administration > Groupe > Attribué à > Oui) sinon ce message d'erreur apparaîtra.

Cette fonction obligeant à avoir un groupe sera changé par la suite mais cela est actuellement nécessaire.

Cordialement.

**Comment by TechGLPI** [comment]
J'ai toujours le message, tout les groupes sur les entités sont avec Attribué à sur oui.

**Comment by YannickComba** [comment]
Pouvez-vous me confirmer que le ticket que vous essayez de transférer se situe bien sur une entité différente que celle sur laquelle vous voulez la transférer ?

**Comment by TechGLPI** [comment]
oui je confirme

**Comment by TechGLPI** [comment]
j'ai fait un essai de bouger un groupe sur une autre entité, et j'ai plus le message d'erreur, il faut que je vois si les autres tickets réagisse. Par contre est il possible d'automatisé le transfert quand un ticket arrive dans un groupe bien définit

**Comment by YannickComba** [comment]
Je vous remercie de votre retour,

Le problème se situe donc au niveau de la configuration entité / groupe et non au niveau du plugin.

Pour rappel, afin que le plugin puisse fonctionner, il faut :

	- Un ticket présent dans une entité A, assigné au technicien ou au groupe du technicien
	- Une entité B avec un groupe ayant le droit "Attribué à" à oui
	- Le droit actif dans Administration > Profils

Sur cette configuration, le transfert de l'entité A vers l'entité B sera possible.
Si vous souhaitez ensuite faire le transfert de l'entité B vers l'entité A, il faudra aussi que l'entité B possède un groupe ayant le droit "Attribué à" à oui.

Concernant votre demande d'automatisation du transfert, cela n'est pas prévu et n'est pas non plus le but du plugin. Votre demande devrait pouvoir être réalisable via les règles natives de GLPI.

Pouvez-vous me confirmer si votre problème a pu être résolu à l'aide des éléments communiqués ?

Cordialement.

**Comment by TechGLPI** [comment]
problème résolu, pour le plugin
