### ISSUE TITLE
Transfert d'un nouveau ticket

### ISSUE THREAD

**Issue by Jerome057** [departement-maine-et-loire/transferticketentity#12]
Bonjour,

Déjà, merci pour ce plugin qui nous soulage bien le travail. 

Est-il possible ou prévu, dans une évolution, de transférer un ticket qui n'est pas encore assigné à un technicien ? 

Merci d'avance

**Comment by YannickComba** [comment]
Bonjour,
 
Merci pour votre retour, il est effectivement prévu de rajouter une option dans les profils qui permettrait aux techniciens liés au profil en question de ne pas avoir besoin de s'assigner/assigner son groupe sur le ticket pour pouvoir le transférer directement.
 
Vous serez notifié par mail via cette issue lors de sa sortie.
 
Cordialement.

**Comment by YannickComba** [comment]
Bonjour,

La version 1.1.1 est disponible.
Merci pour votre retour.

Cordialement.

**Comment by Jerome057** [comment]
Bonjour,

Merci pour la correction, ça fonctionne. 
J'ai directement passé la dernière version ce matin. 
Je vais ouvrir deux autres issues pour une évolution et une correction d'erreur, je pense. 

Cordialement,
