### ISSUE TITLE
The ITIL category is being replicated in the destination entity when transferring tickets between entities.

### ISSUE THREAD

**Issue by thallestorchi** [departement-maine-et-loire/transferticketentity#13]
When escalating a ticket with the ITIL category set to another entity, GLPI creates the current ITIL category of the ticket in the other entity to which the ticket is transferred. This behavior is undesirable, and it would be preferable to have the option to set the category as null when transferring the ticket between entities.

If it is possible to implement in the 'transferticketentity' plugin the ability to set the ITIL category to null before performing the entity transfer operation, it would already be a viable option.

**Comment by thallestorchi** [comment]
Version of GLPI 10.0.9
Version of transferticketentity 1.0.3

**Comment by YannickComba** [comment]
Hello,

Version 1.1.1 is now available.
Thank's for your feedbacks.

Regards.

**Comment by thallestorchi** [comment]
Very good! Thanks! it works fine!
