### ISSUE TITLE
No entity available found, transfer impossible

### ISSUE THREAD

**Issue by infraoderco** [departement-maine-et-loire/transferticketentity#15]
Hello, like the title, I've got the error "No entity available found, transfer impossible" when I try move a ticket.
I have 10.0.11 version of GLPI.

**Comment by YannickComba** [comment]
Hello,

This error message appears when the plugin cannot find any entity to perform the transfer.

Can you check if :

- In administration > entity: 2 or more are configured with at least "Allow transfer function" parameter set to yes ?

This should resolve your issue.

Regards.

**Comment by YannickComba** [comment]
Configuration issue
