### ISSUE TITLE
Message d'erreur affiché en permanence

### ISSUE THREAD

**Issue by Jerome057** [departement-maine-et-loire/transferticketentity#22]
Bonjour,

Depuis le passage sur la version 1.1.2, dans l'onglet transfert de ticket depuis mon ticket, ce message apparait en permanence : 

"Aucun groupe avec le droit « Assigné à » n'a été trouvé alors qu'un groupe est requit. Transfert impossible."

![image](https://github.com/departement-maine-et-loire/transferticketentity/assets/4905764/efc225eb-fac7-404f-9558-9ddc476da007)

Merci d'avance

Jérôme

**Comment by YannickComba** [comment]
Bonjour,

Ce message d'erreur apparaît lorsque dans administration > entité > votreEntité > Transfert d'entité > Groupe à assigner obligatoire est à oui.
Dans ce cas, vos groupes devront avoir le paramètre "Attribué à" à oui.

Je vous laisse vérifier si cela est fonctionnel.

Cordialement.

**Comment by Jerome057** [comment]
Bonjour,

J'ai bien vérifié et tous les paramètres sont bons. Cependant, j'ai l'impression qu'avec la dernière mise à jour de GLPI (10.0.0.12) le message a disparu...

Bonne journée
Jérôme

**Comment by YannickComba** [comment]
Bonjour,

Tant mieux dans ce cas, n'hésitez pas à ouvrir une nouvelle issue si ce problème venait à survenir de nouveau.

Bonne journée.
