### ISSUE TITLE
Evolution : choix d'une catégorie par défaut pour les transferts

### ISSUE THREAD

**Issue by Jerome057** [departement-maine-et-loire/transferticketentity#23]
Bonjour,

Suite à la mise à jour, serait-il possible de pouvoir définir une catégorie par défaut pour les transferts de ticket ? 

J'explique : aujourd'hui quand je transfère un ticket, je corrige d'abord la catégorie en la définissant sur une catégorie "Réorientation" que j'ai créé dans l'entité racine. Ensuite, je réalise le transfert. 

Est-ce possible de pouvoir choisir la catégorie ITIL par défaut lorsque la catégorie du ticket n'existe pas dans l'entité cible (Remplacer la valeur nulle par une catégorie existante) ?

En vous remerciant par avance

Bien cordialement,
Jérôme

**Comment by YannickComba** [comment]
Bonjour,

La nouvelle version comprenant votre demande est disponible, merci pour votre retour.

Cordialement.
