### ISSUE TITLE
Improvement - Justification required option

### ISSUE THREAD

**Issue by andrepetinga** [departement-maine-et-loire/transferticketentity#24]
Hello.
Whether I choose "Justification Required" = Yes or No, when I try to transfer the ticket, it always asks me for a justification, with the "Please explain your transfer" textbox

![image](https://github.com/departement-maine-et-loire/transferticketentity/assets/43515938/7178a880-0ef6-42f6-837a-5f3b8af5b551)

In my point of view, if I select No, it shouldn't present me with this, right?

EDITED:
Ok, my mistake...
If No is selected, the field is presented, but not mandatory...

So my suggestion is to hide the textbox if No is selected.

**Comment by YannickComba** [comment]
Hello,

The justification, even if it's not mandatory, must be displayed by default. It is either obligatory (red border) or optional (blue border). During the next release of the plugin, the notion of optional will be indicated in the text displayed in the transfer window.
