### ISSUE TITLE
Improvement/Bug - Incorrect message if Category is mandatory

### ISSUE THREAD

**Issue by andrepetinga** [departement-maine-et-loire/transferticketentity#25]
We have the Category as mandatory on our Ticket Template.

If we try to transfer the ticket with a Category that doesn't exist on the destination entity, it will be reset to "null" as explained in the documentation.

The problem is that the ticket is not transfered, because of the mandatory field "Category" that is set to null.

And below that message, the "successful transfer for ticket xxx" show up, but it's not correct, because in this case, the ticket remains in the same entity as before...

![image](https://github.com/departement-maine-et-loire/transferticketentity/assets/43515938/5471b007-81bc-4fbd-bdb0-1e0cd23277d7)

Other problem is that a private task shows up saying the ticket was escalated to entity xxx, and this is also wrong.

![image](https://github.com/departement-maine-et-loire/transferticketentity/assets/43515938/bebc8297-7044-4982-92c3-1289fd8895e0)

**Comment by andrepetinga** [comment]
> * What version of TransferTicketEntity is used ?

1.1.2

> * Does the profile with which you tried the transfer have update rights on tickets?

Yes. If I choose a category which exists on the top entitie, and shared with all entities, the transfer works fine. The problem only occurs when the category is set to null.

> * How did you make the category mandatory ? Via GLPI or a plugin (e.g. Behavior) ? Version ?

Via GLPI, with the ticket template. 

![image](https://github.com/departement-maine-et-loire/transferticketentity/assets/43515938/9af586a2-29b0-43e6-bcb3-3a9d74430943)

With Behavior plugin (version 2.7.3), we only use the "**Category is mandatory before ticket is solved/closed**", which is not the case when transfering the ticket.


> * Can you tell me on which action the category must be entered (creation of the ticket, qualification of the ticket by the technician, etc.) ?

When using the mandatory field on the ticket template, the field (category in this case) must be entered:

- when we create a ticket using the interface;
- when we update a ticket, created by the mailgate.

And yes, I agree with you when you say "It doesn't seems to be a transferticketentity issue since it doesn't require a mandatory category.". The mandatory field error is because of the Ticket Template configuration.
I'm guessing you just have to find a way to prevent the "**successful transfer for ticket xxx**" message to show up and also prevent the creation of the private task.

One other thing! If we choose a team from the other entitie, there is also a problem in this case, because the ticket is not transfered, but the team changes to the one that we have choosen from the destination entitie. This means that the ticket remains on the original entitie, but the Assigned to group belongs to other entitie. So you should also prevent this.

Regards

**Comment by bolivarf** [comment]
The same thing happened to me too, I think that if we say that you do not Keep category after transfer you should request it as the technical group asks of you and if you not keep it, do not allow it if there is no category at the destination.

**Comment by Windayz** [comment]
Hello, same problem here. I have rollback the plugin on your production server.
Have a nice day and thanks for all your hard work (even with this little bug :p).

**Comment by YannickComba** [comment]
Hello,

New version is out, thanks for your feedback.

Regards.
