### ISSUE TITLE
Translate do portuguese

### ISSUE THREAD

**Issue by CarlosCFO** [departement-maine-et-loire/transferticketentity#26]
[pt_BR.zip](https://github.com/departement-maine-et-loire/transferticketentity/files/14790247/pt_BR.zip)
i've translated the language files to portuguese, if you like...

**Comment by YannickComba** [comment]
Hello,

Thanks for your help, it will be add to the next version.

Regards.

**Comment by andrepetinga** [comment]
Hello @YannickComba .
Earlier today I've send you an email regarding this, but for the pt-PT language :)
Here you have the translation for pt-PT.

[pt_PT.zip](https://github.com/departement-maine-et-loire/transferticketentity/files/14838665/pt_PT.zip)
