### ISSUE TITLE
Translation into es_VE

### ISSUE THREAD

**Issue by bolivarf** [departement-maine-et-loire/transferticketentity#27]
I have translated the language files to es_VE, if you want...
[es_VE.zip](https://github.com/departement-maine-et-loire/transferticketentity/files/14825098/es_VE.zip)

**Comment by YannickComba** [comment]
Hello,

Thanks for your help, it will be add to the next version.

Regards.

**Comment by YannickComba** [comment]
Hello,

New version is out, thanks for your feedback.

Regards.
