### ISSUE TITLE
Enhancement - Define a default category for transfer

### ISSUE THREAD

**Issue by andrepetinga** [departement-maine-et-loire/transferticketentity#28]
Hello.
It would be nice to have a place to define a default category for all the transfers.
I'm saying this, because nowadays we already have a category created on the Top entity and with the recursive option. Meaning, every entity has access to it.
So, we explained to the technicians that they MUST choose that category BEFORE transfering the ticket to another entity. Otherwise, GLPI will create the ticket category on the destination entity (the all category tree!!).

So now, with your plugin, we are thinking of using the same shared category, and that is why I rebembered that if we can pre-define the category for all transfers, no mistakes will occur.

Think about it :)
Thanks!!

**Comment by YannickComba** [comment]
Hello,

In next version, admin will be able to choose a default category after transfer.

Regards.

**Comment by YannickComba** [comment]
Hello,

New version is out, thanks for your feedback.

Regards.
