### ISSUE TITLE
1.1.3 - Bug when saving changes on entity

### ISSUE THREAD

**Issue by andrepetinga** [departement-maine-et-loire/transferticketentity#30]
After installing the new version (1.1.3) I went to Entity to see the new options.
When I made a change on the configuration and it "Save", the "Allow Transfer function" always changes to "No".
Checking the sql logs, I saw this:

![image](https://github.com/departement-maine-et-loire/transferticketentity/assets/43515938/4ae3d2ed-aed9-4cff-b799-a1e152ca32ff)

I have this:

![image](https://github.com/departement-maine-et-loire/transferticketentity/assets/43515938/7a6d95b8-4198-4dcc-b8ff-e0f00eb20eca)

When I it Save, it shows this:

![image](https://github.com/departement-maine-et-loire/transferticketentity/assets/43515938/ecea6ac3-fd26-4a3b-baea-6f2360285f92)

Even if I choose a default Entity (not null), the problem remains, because the column "itilcategories_id" is not present on the DB table

![image](https://github.com/departement-maine-et-loire/transferticketentity/assets/43515938/f9f26548-8a62-45b2-b796-f5d8fe5a3f10)

UPDATE:
Just checked the source code, and the column is there

![image](https://github.com/departement-maine-et-loire/transferticketentity/assets/43515938/b3ea9311-c304-4d8d-9872-9fdfa7c881a0)

But I think the problem is that you have the if statement

if (!$DB->TableExists("glpi_plugin_transferticketentity_entities_settings")) {

And since I already had the table from the previous version, it didn't add the new column

**Comment by YannickComba** [comment]
Hello,

Yes it's an issue when plugin is update. Uninstall and install should solve your issue.

Regards.

**Comment by andrepetinga** [comment]
Yes, uninstall and install again worked.
Yes, Ctr + F5 made the "default category" go away, when "Allow Transfer function" is set to "No".

Let me just send you the updated version of the Portuguese (Portugal) locale. I saw 3 new lines :)

[pt_PT.zip](https://github.com/departement-maine-et-loire/transferticketentity/files/14957662/pt_PT.zip)

**Comment by YannickComba** [comment]
Thanks for your help,

We should open a Transifex project soon so it'll be easier for translations later.
For "null" word, it's intentional since it's a state, there's no need for a translation for this word.

Regards.
