### ISSUE TITLE
Group selection mandatory although configuration parameter set to No

### ISSUE THREAD

**Issue by enumanc** [departement-maine-et-loire/transferticketentity#37]
![issue-1](https://github.com/departement-maine-et-loire/transferticketentity/assets/1041828/19bd6b4f-9583-4580-8bd7-baceefc4cc08)

![issue-2](https://github.com/departement-maine-et-loire/transferticketentity/assets/1041828/b915900b-fc6d-4416-bd0f-60237350131d)

When transfering a ticket, the group parameter is requested although the parameter is set to 'No' in the configuration

**Comment by enumanc** [comment]
![Uploading issue-2.jpg…]()

**Comment by enumanc** [comment]
Same issue with the category paramater that is set to "Conserver", when transfering a ticket, I have the following error:
![issue-3](https://github.com/departement-maine-et-loire/transferticketentity/assets/1041828/fc207e59-9497-422c-b91d-537358c1fd81)

**Comment by enumanc** [comment]
It seems that for Groups and Categories, if they are not belonging to the entity selected then we have the error.
Is it relevant ? Because our configuration have Groups and Categories configured under the ROOT entity BUT with the sub-entities configured to YES but the plugin seems to ignore this configuration.

**Comment by YannickComba** [comment]
Hello,

For the parameter indicating the group to select, if it is set to "No" this means that it's
possible to not assign any group as shown below, but it's also possible to assign one if necessary.

![Capture1](https://github.com/departement-maine-et-loire/transferticketentity/assets/136609218/c2ec475c-bfa5-4bf9-a971-16c1a2ea3243)

For your 2nd error, you indicate that you want to keep the category when you transfer the ticket but it doesn't exist in the destination entity, thus causing the error message you see.

For more information, please see the README file : 
https://raw.githubusercontent.com/departement-maine-et-loire/transferticketentity/master/README.md

**Comment by enumanc** [comment]
Understood, regarding the point 2, what about the sub-entities parameter on the categories ? If set to YES then the categories declared in the root entity should be seen by the sub-entities. I understand the plugin does not allow that. Would it be relevant to improve it in order to allow transferring ticket to entities with categories's sub-entities paraleter is set to YES ?

**Comment by YannickComba** [comment]
If I understood your point correctly :

You have a parent entity with a category "x" and you want to transfer your ticket to your child entity, which must keep the same category as its parent, is that right?

If so, it's already possible. Your "x" category must be configured to accept Child Entities (visible in Configuration > Dropdowns > Assistance > ITIL Categories > "x" then check Child Entities above)

![Capture](https://github.com/departement-maine-et-loire/transferticketentity/assets/136609218/dbc0f52f-03a7-494a-aa39-d206d58b1538)

Regards.

**Comment by enumanc** [comment]
Bonjour Yannick,

Merci pour votre réponse.

Cependant, les catégories ITL ont bien le paramètre 'Sous-entité' = Oui et
pourant il m'est impossible de transféré un ticket dans une autre entité:
[image: image.png]

Version de GLPI: 10.0.16

Cdlt,
Emmanuel

Le ven. 19 juil. 2024 à 22:51, YannickComba ***@***.***> a
écrit :
