### ISSUE TITLE
Compatibility with GLPI 10

### ISSUE THREAD

**Issue by Fanch-Aldaron** [departement-maine-et-loire/transferticketentity#38]
Hello,

It doesn't say whether your plugin is compatible with GLPI 10, is this the case?
If not, are you planning an update?

Because i have this error when i install tje plugin : 
![image](https://github.com/departement-maine-et-loire/transferticketentity/assets/127228718/7b174319-0430-4065-9974-74f4a2c3a5a0)

version of my GLPI10 : Operating system: Windows NT PAPGLPI10T1 10.0 build 17763 (Windows Server 2019) / PHP 8.2.13 apache2handler

Regards
François

**Comment by YannickComba** [comment]
Hello,

It seems you're making a mistake, you're using the plugin **tickettransfer**, which is different from this one (**transferticketentity**).
Yes the plugin **transferticketentity** is compatible with GLPI 10, the one you're using seems to be this one : https://github.com/Etiennef/tickettransfer (which is different)

You can check on GLPIs plugins page to download the right one : https://plugins.glpi-project.org/#/plugin/transferticketentity

Regards.

**Comment by Fanch-Aldaron** [comment]
ok, i resolv the problem, the issue can be close
